---

- name: fix google pulic key
  import_tasks: fix-apt-google-pubkey.yml

# https://cloud.google.com/sdk/docs/install#deb

- name: prereq packages
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: is google key already loaded into keyring
  command: apt-key list --list-signatures
  register: google_key

# another way to fix public key errors
# https://askubuntu.com/questions/13065/how-do-i-fix-the-gpg-error-no-pubkey
# gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv 9BDB3D89CE49EC21
# gpg --export --armor 9BDB3D89CE49EC21 | sudo apt-key add -
#
# https://launchpad.net/~cloud-images/+archive/ubuntu/docker1903-k8s
- name: get google key because pubkey not found in apt-key list
  shell: curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  when: not item in google_key.stdout and not apt_proxy is defined
  loop:
    - 6A030B21BA07F4FB
    - 5E700FE3D36CFC37
    - FEEA9169307EA071
    - 8B57C5C2836F4BEB

- name: add google repository
  apt_repository:
    repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
    state: present
    filename: google-cloud-sdk
    update_cache: yes
    mode: 0644
    #validate_certs: no

# etc/apt/sources.list.d/docker-ppa.list will change because label change in ppa
# it will need to be rewritten by apt to:
# deb http://ppa.launchpad.net/cloud-images/docker1903-k8s/ubuntu bionic main
- name: do apt update to fix issues with docker ppa changing label (apt-get will not fix)
  command:
    cmd: apt update -y

#- name: install google cloud sdk with apt (and not component manager enabled)
#  package:
#    name:
#      - google-cloud-sdk
#    state: present
#    update_cache: yes

- name: install kubectl and anthos-auth using apt, because we used apt to install google-cloud-sdk and component manager not enabled when you do that
  package:
    name:
      - kubectl
      #- google-cloud-sdk-anthos-auth
    state: present
    update_cache: yes
